controller_manager:
  ros__parameters:

    update_rate: 100

    controller_names:
      - joint_state_broadcaster
      - diff_drive_controller

    joint_state_broadcaster.type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller.type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_joint", "rear_left_joint"]
    right_wheel_names: ["front_right_joint", "rear_right_joint"]
    wheel_separation: 0.27
    wheel_radius: 0.065

    use_stamped_vel: false
    base_frame_id: base_link
    cmd_vel_timeout: 0.25
    publish_rate: 50.0
    enable_odom_tf: false
