controller_manager:
  ros__parameters:
    update_rate: 50

    hardware_platform:
      type: "rugged_rover_hardware_interfaces/sabertooth/SabertoothSystemInterface"
      joints:
        - front_left_joint
        - front_right_joint
      state_interfaces:
        - velocity
      command_interfaces:
        - velocity

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

    diff_drive_controller:
      type: "diff_drive_controller/DiffDriveController"
      left_wheel_names: ["front_left_joint"]
      right_wheel_names: ["front_right_joint"]
      wheel_separation: 0.3
      wheel_radius: 0.1
      base_frame_id: base_link