controller_manager:
  ros__parameters:
    update_rate: 50

    hardware_platform:
      type: "rugged_rover_hardware_interfaces/sabertooth/SabertoothSystemInterface"
      joints:
        - front_left_joint
        - front_right_joint
      state_interfaces:
        - velocity
      command_interfaces:
        - velocity

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"


    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["left_front_wheel_joint", "left_rear_wheel_joint"]
      right_wheel_names: ["right_front_wheel_joint", "right_rear_wheel_joint"]
      wheel_separation: 0.4  # Match your URDF value (meters between left and right wheels)
      wheel_radius: 0.065     # Match your URDF wheel radius (in meters)
      base_frame_id: base_link
      cmd_vel_timeout: 0.5
      use_stamped_vel: false
      publish_rate: 50.0