<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="rugged_rover">

  <!-- Parameters -->
  <xacro:property name="chassis_length" value="0.35"/>
  <xacro:property name="chassis_width" value="0.27"/>
  <xacro:property name="chassis_height" value="0.08"/>
  <xacro:property name="wheel_radius" value="0.065"/>
  <xacro:property name="wheel_width" value="0.03"/>
  <xacro:property name="wheel_x_offset" value="${chassis_length / 2 - 0.05}"/>
  <xacro:property name="wheel_y_offset" value="${chassis_width / 2 + 0.05}"/>
  <xacro:property name="wheel_z_offset" value="${0 - chassis_height / 2}"/>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="Black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
        ixx="0.1" ixy="0.0" ixz="0.0"
        iyy="0.1" iyz="0.0"
        izz="0.1"/>
    </inertial>
  </link>

  <!-- Wheel Macro -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.3"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia
          ixx="0.01" ixy="0.0" ixz="0.0"
          iyy="0.01" iyz="0.0"
          izz="0.01"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${wheel_z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Four Wheels -->
  <xacro:wheel name="left_front_wheel"  x="${ wheel_x_offset}" y="${ wheel_y_offset}"/>
  <xacro:wheel name="right_front_wheel" x="${ wheel_x_offset}" y="${-wheel_y_offset}"/>
  <xacro:wheel name="left_rear_wheel"   x="${-wheel_x_offset}" y="${ wheel_y_offset}"/>
  <xacro:wheel name="right_rear_wheel"  x="${-wheel_x_offset}" y="${-wheel_y_offset}"/>

  <!-- ros2_control: mock interface for joint position -->
  <ros2_control name="RuggedRoverControl" type="system">
    <hardware>
      <plugin>rugged_rover_hardware_interfaces/RuggedRoverHardwareInterface</plugin>
    </hardware>
    <joint name="front_left_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_right_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_left_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_right_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

</robot>