name: CI

on: [push, pull_request]

jobs:
  ros_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install

      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test
          colcon test-result --verbose

      - name: Run clang-format
        run: |
          find . -iname '*.cpp' -o -iname '*.hpp' | xargs clang-format -i --dry-run --Werror
