name: Clang Format Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt install -y clang-format

      - name: Run clang-format check
        run: |
          find . \( -name '*.cpp' -o -name '*.hpp' \) -exec clang-format -n --Werror --style=file {} +

